version: '3.7'

services:
    nginx:
      build: ./nginx
      ports:
        - 1300:80
      volumes:
        - static_volume:/home/app/microservice/static
      depends_on:
        - web
      restart: "on-failure"
    
    db:
      image: postgres:11-alpine
      volumes:
        - ./init_database.sh:/docker-entrypoint-initdb.d/init.sql
        - postgres_data:/var/lib/postgresql/data/
      restart: "on-failure"
      environment:
        - POSTGRES_PASSWORD=django
        - POSTGRES_DB=andalucia_covid_2019
        - POSTGRES_USER=django   
        - PGPORT=5432   
    web:
      build: .
      command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py collectstatic  --noinput &&
                    gunicorn sampleApp.wsgi:application --bind 0.0.0.0:8000"
      volumes:
        - .:/microservice:rw # map data and files from parent directory in host to microservice directory in docker containe
        - static_volume:/home/app/microservice/static
      env_file:
        - .env
      ports:
        - 8000:8000
      env_file:
        - ./.env.dev
      depends_on:
        - db

volumes:
  postgres_data:
  static_volume: